[settings]
timeout = 1000

[relaychain]
default_command = "/Users/gianni/root/Pendulum/polkadot-sdk/target/debug/polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"

[[relaychain.nodes]]
name = "bob"

[[parachains]]
id = 1000
cumulus_based = true
chain = "foucoco" # "pendulum"/"amplitude"/"dev"/"local"

[parachains.collator]
name = "alice"
command = "/Users/gianni/root/Pendulum/pendulum/target/release/pendulum-node"
  
