[package]
authors = ["Pendulum"]
edition = "2021"
name = "module-pallet-staking-rpc"
version = "1.0.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.5" }
jsonrpsee = { version = "0.16.0", features = ["server", "macros"] }
#module-oracle-rpc-runtime-api = { git = "https://github.com/pendulum-chain/spacewalk", default-features = false, rev = "8b41e633321e472288e8fb635a4fc3cde9236d54" }
module-pallet-staking-rpc-runtime-api = { path = "runtime-api" }
sp-api = { version = "21.0.0" }
sp-blockchain = { version = "23.0.0" }
sp-runtime = { version = "26.0.0" }
