
//! Autogenerated weights for orml_tokens_management_extension
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-12-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `pop-os`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("foucoco"), DB CACHE: 1024

// Executed Command:
// ./target/production/pendulum-node
// benchmark
// pallet
// --chain
// foucoco
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// orml-tokens-extension
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/orml-tokens-extension/src/default_weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for orml_tokens_management_extension.
pub trait WeightInfo {
	fn create() -> Weight;
	fn mint() -> Weight;
	fn burn() -> Weight;
	fn transfer_ownership() -> Weight;
	fn set_managers() -> Weight;
}

/// Weights for orml_tokens_management_extension using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3623`
		// Minimum execution time: 32_953_000 picoseconds.
		Weight::from_parts(34_729_000, 3623)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:0)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(70), added: 2545, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `608`
		//  Estimated: `14366`
		// Minimum execution time: 53_859_000 picoseconds.
		Weight::from_parts(106_921_000, 14366)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:0)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(70), added: 2545, mode: MaxEncodedLen)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `770`
		//  Estimated: `10773`
		// Minimum execution time: 78_386_000 picoseconds.
		Weight::from_parts(108_287_000, 10773)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3623`
		// Minimum execution time: 32_848_000 picoseconds.
		Weight::from_parts(40_037_000, 3623)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn set_managers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3623`
		// Minimum execution time: 22_893_000 picoseconds.
		Weight::from_parts(45_341_000, 3623)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn create() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `76`
		//  Estimated: `3623`
		// Minimum execution time: 32_953_000 picoseconds.
		Weight::from_parts(34_729_000, 3623)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:0)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(70), added: 2545, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn mint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `608`
		//  Estimated: `14366`
		// Minimum execution time: 53_859_000 picoseconds.
		Weight::from_parts(106_921_000, 14366)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:0)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	/// Storage: Tokens Accounts (r:1 w:1)
	/// Proof: Tokens Accounts (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// Storage: Tokens TotalIssuance (r:1 w:1)
	/// Proof: Tokens TotalIssuance (max_values: None, max_size: Some(70), added: 2545, mode: MaxEncodedLen)
	fn burn() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `770`
		//  Estimated: `10773`
		// Minimum execution time: 78_386_000 picoseconds.
		Weight::from_parts(108_287_000, 10773)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn transfer_ownership() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3623`
		// Minimum execution time: 32_848_000 picoseconds.
		Weight::from_parts(40_037_000, 3623)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: OrmlExtension CurrencyData (r:1 w:1)
	/// Proof: OrmlExtension CurrencyData (max_values: None, max_size: Some(158), added: 2633, mode: MaxEncodedLen)
	fn set_managers() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3623`
		// Minimum execution time: 22_893_000 picoseconds.
		Weight::from_parts(45_341_000, 3623)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}