
//! Autogenerated weights for dia_oracle
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-09-11, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Gianfrancos-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("foucoco"), DB CACHE: 1024

// Executed Command:
// ./target/production/pendulum-node
// benchmark
// pallet
// --chain
// foucoco
// --wasm-execution=compiled
// --pallet
// dia-oracle
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/amplitude/src/weights/
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for dia_oracle.
pub trait WeightInfo {
	fn add_currency() -> Weight;
	fn remove_currency() -> Weight;
	fn authorize_account() -> Weight;
	fn authorize_account_signed() -> Weight;
	fn deauthorize_account() -> Weight;
	fn deauthorize_account_signed() -> Weight;
	fn set_updated_coin_infos() -> Weight;
	fn set_batching_api() -> Weight;
}

/// Weights for dia_oracle using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::SupportedCurrencies` (r:1 w:1)
	/// Proof: `DiaOracleModule::SupportedCurrencies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `472`
		//  Estimated: `3937`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3937)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::SupportedCurrencies` (r:1 w:0)
	/// Proof: `DiaOracleModule::SupportedCurrencies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `472`
		//  Estimated: `3937`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3937)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3770`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3770)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:2 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn authorize_account_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `6298`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 6298)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deauthorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3770`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3770)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:2 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deauthorize_account_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `6298`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 6298)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::CoinInfosMap` (r:0 w:1)
	/// Proof: `DiaOracleModule::CoinInfosMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_updated_coin_infos() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 9_498_000_000 picoseconds.
		Weight::from_parts(9_560_000_000, 3823)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::BatchingApi` (r:0 w:1)
	/// Proof: `DiaOracleModule::BatchingApi` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_batching_api() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3823)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::SupportedCurrencies` (r:1 w:1)
	/// Proof: `DiaOracleModule::SupportedCurrencies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn add_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `472`
		//  Estimated: `3937`
		// Minimum execution time: 14_000_000 picoseconds.
		Weight::from_parts(15_000_000, 3937)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::SupportedCurrencies` (r:1 w:0)
	/// Proof: `DiaOracleModule::SupportedCurrencies` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn remove_currency() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `472`
		//  Estimated: `3937`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3937)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn authorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3770`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 3770)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:2 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn authorize_account_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `6298`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 6298)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deauthorize_account() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `305`
		//  Estimated: `3770`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 3770)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:2 w:1)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deauthorize_account_signed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `6298`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(12_000_000, 6298)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::CoinInfosMap` (r:0 w:1)
	/// Proof: `DiaOracleModule::CoinInfosMap` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn set_updated_coin_infos() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 9_498_000_000 picoseconds.
		Weight::from_parts(9_560_000_000, 3823)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `DiaOracleModule::AuthorizedAccounts` (r:1 w:0)
	/// Proof: `DiaOracleModule::AuthorizedAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `DiaOracleModule::BatchingApi` (r:0 w:1)
	/// Proof: `DiaOracleModule::BatchingApi` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn set_batching_api() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `358`
		//  Estimated: `3823`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(11_000_000, 3823)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}