//! Autogenerated weights for `token_migration`.
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-08-27, STEPS: `50`, REPEAT: `20`
//! WASM-EXECUTION: `Compiled`, DB CACHE: 1024
//!
//! Generated on a development machine, not on collator-grade reference
//! hardware, and accepted as the production weights (decision 2026-09-06):
//! the project has never benchmarked on reference hardware, and these are
//! measured rather than hand estimated. Regenerate if the pallet's
//! extrinsics change.
//!
//! Regenerate with:
//!
//! ```text
//! cargo build --release --features runtime-benchmarks -p pendulum-node
//! ./target/release/pendulum-node benchmark pallet \
//!     --chain <spec> --pallet token-migration --extrinsic '*' \
//!     --steps 50 --repeat 20 \
//!     --template .maintain/frame-weight-template.hbs \
//!     --output pallets/token-migration/src/default_weights.rs
//! ```
//!
//! NOTE: `--chain pendulum` currently fails for every pallet in this repo with
//! `Invalid JSON blob: unknown variant ...`. `CurrencyId` and `OracleKey`
//! serialise their variants first-letter-lowercased (`native`, `xCM`,
//! `exchangeRate`) but deserialise expecting the original casing, so the
//! benchmark CLI cannot read back the genesis it just built. Until that is
//! fixed upstream, generate a spec with `build-spec`, rewrite those variant
//! names to their PascalCase form, and pass the patched file as `--chain`.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `token_migration`.
pub trait WeightInfo {
	fn migrate() -> Weight;
	fn set_paused() -> Weight;
	fn set_treasury_destination() -> Weight;
	fn migrate_treasury() -> Weight;
}

/// Weights for `token_migration` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TokenMigration::Paused` (r:1 w:0)
	/// Proof: `TokenMigration::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenMigration::NextNonce` (r:1 w:1)
	/// Proof: `TokenMigration::NextNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TokenMigration::TotalMigrated` (r:1 w:1)
	/// Proof: `TokenMigration::TotalMigrated` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn migrate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `166`
		//  Estimated: `1501`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(19_000_000, 1501)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `TokenMigration::Paused` (r:0 w:1)
	/// Proof: `TokenMigration::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 3_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenMigration::TreasuryDestination` (r:1 w:1)
	/// Proof: `TokenMigration::TreasuryDestination` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	fn set_treasury_destination() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `515`
		// Conservative until the next production-hardware regeneration: the
		// one-time-set guard adds one storage read and its proof.
		Weight::from_parts(6_000_000, 515)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `TokenMigration::Paused` (r:1 w:0)
	/// Proof: `TokenMigration::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `TokenMigration::TreasuryDestination` (r:1 w:0)
	/// Proof: `TokenMigration::TreasuryDestination` (`max_values`: Some(1), `max_size`: Some(20), added: 515, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `TokenMigration::NextNonce` (r:1 w:1)
	/// Proof: `TokenMigration::NextNonce` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `TokenMigration::TotalMigrated` (r:1 w:1)
	/// Proof: `TokenMigration::TotalMigrated` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn migrate_treasury() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `550`
		//  Estimated: `3593`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(24_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn migrate() -> Weight {
		Weight::from_parts(19_000_000, 1501)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn set_paused() -> Weight {
		Weight::from_parts(4_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn set_treasury_destination() -> Weight {
		Weight::from_parts(6_000_000, 515)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn migrate_treasury() -> Weight {
		Weight::from_parts(24_000_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
