name: Deploy collator node
on:
    push:
        branches:
            - master

jobs:
    build:
        name: Deploy
        runs-on: self-hosted
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Build
              run: docker-compose -f .config/docker-compose-rococo.yml build
