name: Node Version Up

on:
  workflow_dispatch:
    inputs:
      versioning:
        description: "node version up: major, minor, or patch"
        required: true
        default: "patch"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup User
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: install cargo-edit
        run: |
          cargo install cargo-edit
      - name: Set New Version ${{ github.event.inputs.versioning }}
        continue-on-error: false
        run: |
          cargo set-version --bump ${{ github.event.inputs.versioning }} --package pendulum-node
      - name: save updated version
        id: new-version
        run: |
          cd node
          echo "version=$(cargo metadata --format-version=1 --no-deps | jq '.packages[0].version')" >> "$GITHUB_OUTPUT"
          cd ..
      - name: Create Release Branch for version ${{ steps.new-version.outputs.version }}
        id: branch-name
        run: |
          echo "branch_name=release/upgrade-node-to-${{ steps.new-version.outputs.version }}" >> "$GITHUB_OUTPUT"
          git checkout -b release/upgrade-node-to-${{ steps.new-version.outputs.version }}
          git push --set-upstream origin release/upgrade-node-to-${{ steps.new-version.outputs.version }}
      - name: Commit New Changes to New Branch
        run: |
          gh api graphql \
          -F githubRepository=${{ github.repository }} \
          -F branchName=${{ steps.branch-name.outputs.branch_name }} \
          -F expectedHeadOid=$(git rev-parse HEAD) \
          -F commitMessage="chore: node upgrade to ${{ steps.new-version.outputs.version }}" \
          -F files[][path]="node/Cargo.toml" -F files[][contents]=$(base64 -w0 node/Cargo.toml) \
          -F 'query=@.github/api/createCommitOnBranch.gql'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ steps.branch-name.outputs.branch_name }}
      - name: Create Pull Request
        uses: thomaseizinger/create-pull-request@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: "release: upgrade node to ${{ steps.new-version.outputs.version }}"
          head: ${{ steps.branch-name.outputs.branch_name }}
          base: main
          reviewers: "ebma, TorstenStueber, bogdanS98, gianfra-t, b-yap"