# This action triggers a GitLab CI job that performs the following:
# * Srtool Check
# * Subwasm info of the compressed wasm file
# * Generate Release Notes
# * Propose a Parachain Upgrade
name: Release and Propose an Upgrade

#on:
#  pull_request:
#    types:
#      - closed
#    branches:
#      - 'main'
on:
  pull_request:
    branches:
      - main

jobs:
  release_check:
#    This job will only run if:
#     * the pull request is closed and merged to main branch;
#     * the pull request has the "release:" in its title
#    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.title, 'release:') }}
    name: ${{ matrix.chain }} need new release
    strategy:
      fail-fast: true
      matrix:
         chain: ["PENDULUM"]
#        chain: ["AMPLITUDE", "PENDULUM"]
#        shouldReleaseAmp:
#          - ${{ contains(github.event.pull_request.title, 'amplitude') }}
#        shouldReleasePen:
#          - ${{ contains(github.event.pull_request.title, 'pendulum') }}
#        exclude:
#          - shouldReleaseAmp: false
#            chain: "AMPLITUDE"
#          - shouldReleasePen: false
#            chain: "PENDULUM"
    runs-on: ubuntu-latest

    steps:
      - name: trigger gitlab
        uses: eic/trigger-gitlab-ci@v1
        with:
          url: https://gitlab.com
          project_id: 56492543
          token: ${{ secrets.GITLABAPI }}
          ref_name: main
          variables: |
            ${{ matrix.chain }}=Y
