
//! Autogenerated weights for parachain_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-01-06, STEPS: `50`, REPEAT: `5`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Gianfrancos-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: Some("pendulum"), DB CACHE: 1024

// Executed Command:
// ./target/production/pendulum-node
// benchmark
// pallet
// --chain
// pendulum
// --execution=wasm
// --wasm-execution=compiled
// --pallet
// parachain-staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 5
// --output
// runtime/pendulum/src/weights/parachain_staking.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weights for parachain_staking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> parachain_staking::WeightInfo for SubstrateWeight<T> {
	/// Storage: `ParachainStaking::Round` (r:1 w:0)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn on_initialize_no_action() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `1497`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 1497)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `ParachainStaking::Round` (r:1 w:1)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn on_initialize_round_update() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `1497`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 1497)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainStaking::Round` (r:1 w:0)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn on_initialize_network_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `1497`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 1497)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `ParachainStaking::ForceNewRound` (r:0 w:1)
	/// Proof: `ParachainStaking::ForceNewRound` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn force_new_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:41 w:0)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:1640 w:1640)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:40 w:40)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:1)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CounterForCandidatePool` (r:1 w:0)
	/// Proof: `ParachainStaking::CounterForCandidatePool` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 40]`.
	/// The range of component `m` is `[0, 40]`.
	fn set_inflation(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (3891 ±0) + n * (4052 ±0)`
		//  Estimated: `101750 + m * (37911 ±1_929) + n * (33703 ±1_929)`
		// Minimum execution time: 437_000_000 picoseconds.
		Weight::from_parts(438_000_000, 101750)
			// Standard Error: 4_489_447
			.saturating_add(Weight::from_parts(73_971_078, 0).saturating_mul(n.into()))
			// Standard Error: 4_489_447
			.saturating_add(Weight::from_parts(77_225_909, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(124_u64))
			.saturating_add(T::DbWeight::get().reads((14_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((14_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(81_u64))
			.saturating_add(T::DbWeight::get().writes((14_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((14_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 37911).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 33703).saturating_mul(n.into()))
	}
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[8, 40]`.
	/// The range of component `m` is `[0, 40]`.
	fn set_max_selected_candidates(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434 + n * (48 ±0)`
		//  Estimated: `3406`
		// Minimum execution time: 12_000_000 picoseconds.
		Weight::from_parts(13_000_000, 3406)
			// Standard Error: 10_092
			.saturating_add(Weight::from_parts(78_768, 0).saturating_mul(n.into()))
			// Standard Error: 10_379
			.saturating_add(Weight::from_parts(80_361, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ParachainStaking::Round` (r:1 w:1)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	fn set_blocks_per_round() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `427`
		//  Estimated: `1497`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_000_000, 1497)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:40 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:41 w:41)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::DelegatorState` (r:40 w:40)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:41 w:41)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::DisabledValidators` (r:1 w:1)
	/// Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Digest` (r:1 w:1)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainStaking::CounterForCandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CounterForCandidatePool` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[9, 40]`.
	/// The range of component `m` is `[0, 40]`.
	fn force_remove_candidate(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (3151 ±0) + n * (2733 ±0)`
		//  Estimated: `9317 + m * (2716 ±0) + n * (4505 ±50)`
		// Minimum execution time: 148_000_000 picoseconds.
		Weight::from_parts(150_000_000, 9317)
			// Standard Error: 152_463
			.saturating_add(Weight::from_parts(1_867_364, 0).saturating_mul(n.into()))
			// Standard Error: 157_416
			.saturating_add(Weight::from_parts(14_438_314, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(9_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 2716).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 4505).saturating_mul(n.into()))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:0)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxCollatorCandidateStake` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxCollatorCandidateStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CounterForCandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CounterForCandidatePool` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	/// The range of component `m` is `[0, 40]`.
	fn join_candidates(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2202 + m * (45 ±0) + n * (85 ±0)`
		//  Estimated: `5495`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(36_039_100, 5495)
			// Standard Error: 30_569
			.saturating_add(Weight::from_parts(538_019, 0).saturating_mul(n.into()))
			// Standard Error: 29_064
			.saturating_add(Weight::from_parts(528_398, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:39 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Round` (r:1 w:0)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[9, 39]`.
	/// The range of component `m` is `[0, 40]`.
	fn init_leave_candidates(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (1872 ±0) + n * (2082 ±0)`
		//  Estimated: `3406 + n * (4505 ±0)`
		// Minimum execution time: 52_000_000 picoseconds.
		Weight::from_parts(53_000_000, 3406)
			// Standard Error: 44_199
			.saturating_add(Weight::from_parts(2_590_240, 0).saturating_mul(n.into()))
			// Standard Error: 44_528
			.saturating_add(Weight::from_parts(49_081, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 4505).saturating_mul(n.into()))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[9, 39]`.
	/// The range of component `m` is `[0, 40]`.
	fn cancel_leave_candidates(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `774 + m * (48 ±0) + n * (51 ±0)`
		//  Estimated: `5495`
		// Minimum execution time: 22_000_000 picoseconds.
		Weight::from_parts(6_086_601, 5495)
			// Standard Error: 34_725
			.saturating_add(Weight::from_parts(494_527, 0).saturating_mul(n.into()))
			// Standard Error: 26_140
			.saturating_add(Weight::from_parts(451_202, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Round` (r:1 w:0)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:41 w:41)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::DelegatorState` (r:40 w:40)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:41 w:41)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// Storage: `Session::Validators` (r:1 w:0)
	/// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `Session::DisabledValidators` (r:1 w:1)
	/// Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `System::Digest` (r:1 w:1)
	/// Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ParachainStaking::CounterForCandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CounterForCandidatePool` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[9, 39]`.
	/// The range of component `m` is `[0, 40]`.
	fn execute_leave_candidates(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (1267 ±0) + n * (655 ±0)`
		//  Estimated: `5495 + m * (2716 ±0) + n * (209 ±12)`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(40_000_000, 5495)
			// Standard Error: 103_186
			.saturating_add(Weight::from_parts(625_475, 0).saturating_mul(n.into()))
			// Standard Error: 103_956
			.saturating_add(Weight::from_parts(16_576_698, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().reads((3_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(7_u64))
			.saturating_add(T::DbWeight::get().writes((3_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 2716).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 209).saturating_mul(n.into()))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxCollatorCandidateStake` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxCollatorCandidateStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:41 w:41)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	/// The range of component `m` is `[0, 40]`.
	/// The range of component `u` is `[0, 9]`.
	fn candidate_stake_more(n: u32, m: u32, _u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (480 ±0) + n * (291 ±0) + u * (20 ±0)`
		//  Estimated: `5495 + m * (2519 ±0)`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(57_000_000, 5495)
			// Standard Error: 41_210
			.saturating_add(Weight::from_parts(1_044_365, 0).saturating_mul(n.into()))
			// Standard Error: 39_766
			.saturating_add(Weight::from_parts(6_359_253, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(12_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(8_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 2519).saturating_mul(m.into()))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:41 w:41)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 39]`.
	/// The range of component `m` is `[0, 40]`.
	fn candidate_stake_less(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (452 ±0) + n * (278 ±0)`
		//  Estimated: `5495 + m * (2519 ±0)`
		// Minimum execution time: 38_000_000 picoseconds.
		Weight::from_parts(38_000_000, 5495)
			// Standard Error: 34_606
			.saturating_add(Weight::from_parts(526_076, 0).saturating_mul(n.into()))
			// Standard Error: 33_843
			.saturating_add(Weight::from_parts(5_898_655, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(6_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 2519).saturating_mul(m.into()))
	}
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:1)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidatePool` (r:2 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::LastDelegation` (r:1 w:1)
	/// Proof: `ParachainStaking::LastDelegation` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Round` (r:1 w:0)
	/// Proof: `ParachainStaking::Round` (`max_values`: Some(1), `max_size`: Some(12), added: 507, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:1 w:1)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 40]`.
	/// The range of component `m` is `[1, 39]`.
	fn join_delegators(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3558 + m * (112 ±0) + n * (95 ±0)`
		//  Estimated: `10000`
		// Minimum execution time: 67_000_000 picoseconds.
		Weight::from_parts(41_949_854, 10000)
			// Standard Error: 25_840
			.saturating_add(Weight::from_parts(696_617, 0).saturating_mul(n.into()))
			// Standard Error: 26_535
			.saturating_add(Weight::from_parts(716_723, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(13_u64))
			.saturating_add(T::DbWeight::get().writes(9_u64))
	}
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:1)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:2 w:0)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 40]`.
	/// The range of component `m` is `[1, 39]`.
	/// The range of component `u` is `[1, 9]`.
	fn delegator_stake_more(n: u32, m: u32, u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3853 + m * (93 ±0) + n * (87 ±0) + u * (20 ±0)`
		//  Estimated: `6028`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(38_647_691, 6028)
			// Standard Error: 23_440
			.saturating_add(Weight::from_parts(593_215, 0).saturating_mul(n.into()))
			// Standard Error: 24_069
			.saturating_add(Weight::from_parts(679_076, 0).saturating_mul(m.into()))
			// Standard Error: 110_507
			.saturating_add(Weight::from_parts(41_066, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:1)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:2 w:0)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 40]`.
	/// The range of component `m` is `[1, 39]`.
	fn delegator_stake_less(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3028 + m * (74 ±0) + n * (74 ±0)`
		//  Estimated: `6028`
		// Minimum execution time: 40_000_000 picoseconds.
		Weight::from_parts(23_764_844, 6028)
			// Standard Error: 15_425
			.saturating_add(Weight::from_parts(478_945, 0).saturating_mul(n.into()))
			// Standard Error: 15_839
			.saturating_add(Weight::from_parts(540_624, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:1)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:1)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:2 w:0)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TopCandidates` (r:1 w:1)
	/// Proof: `ParachainStaking::TopCandidates` (`max_values`: Some(1), `max_size`: Some(1921), added: 2416, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::MaxSelectedCandidates` (r:1 w:0)
	/// Proof: `ParachainStaking::MaxSelectedCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:1)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[1, 40]`.
	/// The range of component `m` is `[1, 39]`.
	fn leave_delegators(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `3028 + m * (74 ±0) + n * (74 ±0)`
		//  Estimated: `6028`
		// Minimum execution time: 44_000_000 picoseconds.
		Weight::from_parts(16_647_600, 6028)
			// Standard Error: 26_776
			.saturating_add(Weight::from_parts(702_193, 0).saturating_mul(n.into()))
			// Standard Error: 27_495
			.saturating_add(Weight::from_parts(705_726, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ParachainStaking::Unstaking` (r:1 w:1)
	/// Proof: `ParachainStaking::Unstaking` (`max_values`: None, `max_size`: Some(241), added: 2716, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Locks` (r:1 w:1)
	/// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
	/// Storage: `Balances::Freezes` (r:1 w:0)
	/// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `u` is `[1, 9]`.
	fn unlock_unstaked(u: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1246 + u * (20 ±0)`
		//  Estimated: `4764`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(27_350_675, 4764)
			// Standard Error: 16_609
			.saturating_add(Weight::from_parts(75_923, 0).saturating_mul(u.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ParachainStaking::MaxCollatorCandidateStake` (r:0 w:1)
	/// Proof: `ParachainStaking::MaxCollatorCandidateStake` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	fn set_max_candidate_stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ParachainStaking::DelegatorState` (r:1 w:0)
	/// Proof: `ParachainStaking::DelegatorState` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:2 w:1)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	fn increment_delegator_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `754`
		//  Estimated: `6028`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(21_000_000, 6028)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ParachainStaking::CandidatePool` (r:1 w:0)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:41 w:41)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:41 w:41)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:0)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// The range of component `m` is `[1, 40]`.
	fn increment_collator_rewards(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `853 + m * (98 ±0)`
		//  Estimated: `5495 + m * (2531 ±0)`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(17_783_857, 5495)
			// Standard Error: 21_870
			.saturating_add(Weight::from_parts(8_587_219, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 2531).saturating_mul(m.into()))
	}
	/// Storage: `ParachainStaking::Rewards` (r:1 w:1)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_rewards() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `712`
		//  Estimated: `3593`
		// Minimum execution time: 21_000_000 picoseconds.
		Weight::from_parts(21_000_000, 3593)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ParachainStaking::LastRewardReduction` (r:1 w:1)
	/// Proof: `ParachainStaking::LastRewardReduction` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::InflationConfig` (r:1 w:1)
	/// Proof: `ParachainStaking::InflationConfig` (`max_values`: Some(1), `max_size`: Some(96), added: 591, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CandidatePool` (r:41 w:0)
	/// Proof: `ParachainStaking::CandidatePool` (`max_values`: None, `max_size`: Some(2030), added: 4505, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::RewardCount` (r:1640 w:1640)
	/// Proof: `ParachainStaking::RewardCount` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::Rewards` (r:40 w:40)
	/// Proof: `ParachainStaking::Rewards` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::TotalCollatorStake` (r:1 w:0)
	/// Proof: `ParachainStaking::TotalCollatorStake` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `ParachainStaking::CounterForCandidatePool` (r:1 w:0)
	/// Proof: `ParachainStaking::CounterForCandidatePool` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 40]`.
	/// The range of component `m` is `[0, 40]`.
	fn execute_scheduled_reward_change(n: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (3891 ±0) + n * (3991 ±0)`
		//  Estimated: `101750 + m * (37911 ±1_929) + n * (33703 ±1_929)`
		// Minimum execution time: 387_000_000 picoseconds.
		Weight::from_parts(387_000_000, 101750)
			// Standard Error: 4_530_750
			.saturating_add(Weight::from_parts(74_527_494, 0).saturating_mul(n.into()))
			// Standard Error: 4_530_750
			.saturating_add(Weight::from_parts(76_637_417, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(125_u64))
			.saturating_add(T::DbWeight::get().reads((14_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().reads((14_u64).saturating_mul(m.into())))
			.saturating_add(T::DbWeight::get().writes(82_u64))
			.saturating_add(T::DbWeight::get().writes((14_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes((14_u64).saturating_mul(m.into())))
			.saturating_add(Weight::from_parts(0, 37911).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 33703).saturating_mul(n.into()))
	}
}